### ISSUE TITLE
Solve test failures

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-citygml20#19]
When building branch `develop-aries` with `mvn clean install site -Pdocker,integration-tests` following test failure occurs:
```
Results :

Failed tests: 
  VerifyTestNGController.doTestRun:69 Unexpected number of fail verdicts. expected:<0> but was:<5>

Tests run: 22, Failures: 1, Errors: 0, Skipped: 2
```

This failure must be fixed so that above documented command can be executed successfully.

**Comment by jiann** [comment]
The failure solved by adding test data for Maven packaging.

> Commit: [Issue: Solve test failures #19 ](https://github.com/opengeospatial/ets-citygml20/commit/fd76c4ed32a2a41a62cf6e50151b232bc562f13b)

**Comment by dstenger** [comment]
I can confirm that the failures are solved.
